### ISSUE TITLE
TypeError: unsupported operand type(s) for ^: 'int' and 'str'

### ISSUE THREAD

**Issue by random-robbie** [neex/ffmpeg-avi-m3u-xbin#1]
```
python gen_xbin_avi.py file:///etc/password file_read.avi
Traceback (most recent call last):
  File "gen_xbin_avi.py", line 87, in <module>
    SYNC = echo_seq(gen_xbin_sync())
  File "gen_xbin_avi.py", line 81, in echo_seq
    res.append(echo_block(s[i:i + 16]))
  File "gen_xbin_avi.py", line 41, in echo_block
    iv = ''.join(map('{:02x}'.format, [x ^ y for (x, y) in zip(block, GAMMA)]))
TypeError: unsupported operand type(s) for ^: 'int' and 'str'`

```

any ideas on how to resolve this at all?

**Comment by neex** [comment]
The script is for python3, and it seems like you're using python2.

**Comment by random-robbie** [comment]
ah bad spotting by me sorry about that!
thought i had 3 as default
